### ISSUE TITLE
Browsing URLs directly causes a 404

### ISSUE THREAD

**Issue by iamjayrome** [script3/soroban-governor-ui#15]
If you view any of the individual DAO pages directly, or refresh when viewing them, you get a 404.

Example URL producing 404 when accessed directly - https://testnet.governance.script3.io/CCIAMLHDTH3MUZR2KCXRK5JWDBLZL6MBD5AVITLPL73PZIMNOX7SKDSV/proposals

If you start at https://testnet.governance.script3.io/ and click on XLM DAO the page loads fine.

**Comment by mootz12** [comment]
This was resolved in a bundle of bug fixes recently.

Please re-open if you are still having issues!
